/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHELaunchPriceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowDecryption"
      | "encryptedGuessOf"
      | "hasSubmitted"
      | "lastGuessTimestamp"
      | "protocolId"
      | "submitPriceGuess"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PriceGuessSubmitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "allowDecryption",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedGuessOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastGuessTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitPriceGuess",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allowDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedGuessOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastGuessTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitPriceGuess",
    data: BytesLike
  ): Result;
}

export namespace PriceGuessSubmittedEvent {
  export type InputTuple = [participant: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [participant: string, timestamp: bigint];
  export interface OutputObject {
    participant: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHELaunchPrice extends BaseContract {
  connect(runner?: ContractRunner | null): FHELaunchPrice;
  waitForDeployment(): Promise<this>;

  interface: FHELaunchPriceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowDecryption: TypedContractMethod<
    [grantee: AddressLike],
    [void],
    "nonpayable"
  >;

  encryptedGuessOf: TypedContractMethod<[user: AddressLike], [string], "view">;

  hasSubmitted: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  lastGuessTimestamp: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  submitPriceGuess: TypedContractMethod<
    [encryptedGuess: BytesLike, zkProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowDecryption"
  ): TypedContractMethod<[grantee: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "encryptedGuessOf"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastGuessTimestamp"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitPriceGuess"
  ): TypedContractMethod<
    [encryptedGuess: BytesLike, zkProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PriceGuessSubmitted"
  ): TypedContractEvent<
    PriceGuessSubmittedEvent.InputTuple,
    PriceGuessSubmittedEvent.OutputTuple,
    PriceGuessSubmittedEvent.OutputObject
  >;

  filters: {
    "PriceGuessSubmitted(address,uint256)": TypedContractEvent<
      PriceGuessSubmittedEvent.InputTuple,
      PriceGuessSubmittedEvent.OutputTuple,
      PriceGuessSubmittedEvent.OutputObject
    >;
    PriceGuessSubmitted: TypedContractEvent<
      PriceGuessSubmittedEvent.InputTuple,
      PriceGuessSubmittedEvent.OutputTuple,
      PriceGuessSubmittedEvent.OutputObject
    >;
  };
}
